### ISSUE TITLE
Install MongoDB

### ISSUE THREAD

**Issue by MasterOfTheBus** [MasterOfTheBus/FunStuff#1]
Do separately

**Comment by MasterOfTheBus** [comment]
i think i did it. using ubuntu on windows, so i'm using `sudo service mongodb start` to start mongodb instead of `sudo service mongod start` as per the documentation. we should probably push Charles' version of the "hello world" in and i should get a better linux environment

**Comment by chubchubcharles** [comment]
I installed [this](http://mean.io/) but I think this is the lazy way and it's probably not correct, so I'm still trying to get through to installing MongoDB for now....

**UPDATE(01/21)**: I decided not to go through with Mean.io and installed each individually. I verified the MongoDB installation with this [HackHands tutorial](https://hackhands.com/how-to-get-started-on-the-mean-stack/). I could run `mongod` on one terminal to spin up the server, then `mongo` for the MongoDB shell on another terminal to connect to the mongod server and interact on the CLI.
