### ISSUE TITLE
Install Angular.js

### ISSUE THREAD

**Issue by MasterOfTheBus** [MasterOfTheBus/FunStuff#3]
Do separately

**Comment by chubchubcharles** [comment]
There are two versions for Angular: **Angular 1** and **Angular 2**. Based on the response written in [this Quora question](https://www.quora.com/What-is-the-difference-between-AngularJs-and-Angular-2), Angular 2 is a "major upgrade" from Angular 1, and therefore I believe it would be best for us to use **Angular 2**.

**Possible drawbacks:**
* Lack of community resources/tuts
* In beta version, possible with bugs

**Comment by chubchubcharles** [comment]
**Angular 2 Tutorials**:
* [Quickstart](https://angular.io/docs/ts/latest/quickstart.html) - Completed
* [Setup for local development environment](https://angular.io/docs/ts/latest/guide/setup.html) - Completed
* [Guide to Learning Angular](https://angular.io/docs/ts/latest/guide/learning-angular.html) - Incomplete, Should familiarize in the next issues to understand how to use Angular 2 with TypeScript. For example, I don't know how 'Modules', 'Components', and 'Templates' are used. **I will create another issue that makes us get our hands dirty in understanding the basics of Angular 2 but not become too engrossed in the specifics.**
