### ISSUE TITLE
Create a "Exercise" Model

### ISSUE THREAD

**Issue by chubchubcharles** [MasterOfTheBus/FunStuff#7]
** **NOTE: Should begin after development environment setup completed.** **

**Implement the CRUD features for an Exercise, like so:**
* Example: { Book : "Some Classic", Scale: "C Major", Exercise: "Triads and Inversions"}

**Exit Criteria:**
* Can Create books on another page "/users/:userID/books" for users who are logged in.
* Can View books on a page "/users/:userID/books/" with a list of exercises in whatever format (text, etc.)
* Can Update books on the page "/users/:userID/books/" by renaming the exercises
* Can Delete books on the page "/users/:userID/books/"

**UPDATE (02/04/2017):** I meant to say 'exercises' for 'books' in the exit criteria.

**Comment by chubchubcharles** [comment]
** UPDATE (02/01)**
It's after Chinese New Year vacation now, I still have to do this.... lol

**Comment by MasterOfTheBus** [comment]
http://mongoosejs.com/docs/api.html#query_Query-find

so I don't have to look for this link again

**Comment by chubchubcharles** [comment]
I am trying to test CRUD on "exercises" using the mongo shell, but I cannot find an "exercises" collection, whereas "users" has a collection...

I thought it may be because I needed to insert an "exercise" document in order to generate an "exercise" collection, but I didn't have to do that with "users" upon startup, so I think it has to do with some startup code that creates only "users" collection, but not "exercises" collection..

**Comment by chubchubcharles** [comment]
Nevermind, you really have to insert a document in order to start a collection.

**Comment by chubchubcharles** [comment]
We need a user interface for CRUD-ing exercises and also associate the User and Exercise models together.

**Comment by MasterOfTheBus** [comment]
yeah I agree. we may need to sync up about this

**Comment by chubchubcharles** [comment]
Regarding how to associate User and Exercise models:

I first read [Data Modeling Introduction](https://docs.mongodb.com/manual/core/data-modeling-introduction/) to learn that in MongoDB the key decision to figuring out between mapping relationships  between entities is whether to go with: ***references***  or ***embedded documents***. 

I wanted to understand the advantages and disadvantages of using *references* and *embedded documents* [here](https://docs.mongodb.com/manual/tutorial/model-referenced-one-to-many-relationships-between-documents/) and [here](https://docs.mongodb.com/manual/tutorial/model-embedded-one-to-many-relationships-between-documents/).

Before I talk about the User and Exercise, I can confidently answer that for Exercises and Book in our later decision, we should use ***references*** instead of ***embedded documents***. It mirrors the analogy [here](https://docs.mongodb.com/manual/tutorial/model-referenced-one-to-many-relationships-between-documents/) with Books and a common Publisher. 

For User and Exercise, I think we should use ***embedded documents*** because for each User, which has **many** exercises, we will regularly query the User first, and then upon that peruse over the Exercises it has completed/"needs learning"/etc. 

What do you think?

**Comment by chubchubcharles** [comment]
Since you've implemented the MongoDB functionalities for **Exercises**, I think we can close it.

@MasterOfTheBus close if you think it's good!

**Comment by MasterOfTheBus** [comment]
k we've got the issue in to modify exercises, so i'll close this out
